---
api:
  development:
    hostname: 0.0.0.0
    port: 8080
    workers: 5
    reloader: true
    debug: true

  production:
    hostname: 0.0.0.0
    port: 8080
    workers: 10
    reloader: false
    debug: false