---
- name: Install Dependencies - Core
  run: make install

- name: Install Dependencies - App
  run: invoke deps

- name: Run Lint
  run: invoke lint

- name: Run Unit
  run: invoke unit

- name: Deploy
  run: invoke deploy --target development
  branch: development

- name: Deploy
  run: invoke deploy --target production
  branch: production
